@host = http://localhost:3000
@projectId = b.76947f01-cc26-47db-9681-fff27e5430ce
@projectId2= b.611f0303-7b8a-4f45-99f1-5da93b802707
@hubId = b.1bb899d4-8dd4-42d8-aefd-6c0e35acd825
@urnId= dXJuOmFkc2sud2lwcHJvZDpmcy5maWxlOnZmLnFSbHZQSFFoUmd5b0NFd0NsM2VFbGc_dmVyc2lvbj0y
@urnId2= dXJuOmFkc2sud2lwcHJvZDpmcy5maWxlOnZmLm9fb2pBVGRMVHRPZ3lRTVJvbk1lakE_dmVyc2lvbj0x
@itemId= urn:adsk.wipprod:dm.lineage:o_ojATdLTtOgyQMRonMejA
@itemId2= urn:adsk.wipprod:dm.lineage:qRlvPHQhRgyoCEwCl3eElg
@urlAuth = /api/auth
@urlHub = /api/hub
@urlProjects = /api/projects
@urlFiles = /files
@urlRoot = /api/root
@urlProperties = /api/properties
@urlModels = /api/model


###################
### ACCESSTOKEN ###
###################

GET {{host}}{{urlAuth}}

###########
### HUB ###
###########

GET {{host}}{{urlHub}}

################
### PROJECTS ###
################

### Listar todos los proyectos
GET {{host}}{{urlProjects}}/{{hubId}}

### listar recursivamente todos las subcarpetas y ficheros finales del proyecto
GET {{host}}{{urlRoot}}/{{hubId}}/{{projectId}}{{urlFiles}}

### Listar el proyecto by Id
GET {{host}}{{urlProjects}}/{{hubId}}/{{projectId}}

### Obtener el Version ID del fichero
GET {{host}}{{urlRoot}}/{{projectId}}/{{itemId2}}/versionId

### Metadata of .rvt
GET {{host}}{{urlProperties}}/meta/{{urnId2}}/metadata

### Elements
GET {{host}}{{urlProperties}}/{{projectId}}/{{urnId}}/allElements

### Hard Elements
GET {{host}}{{urlProperties}}/{{urnId}}/387999db-2c35-0c10-bea9-76f78ea2d06e/allElementsHard

### Model Objects
GET {{host}}{{urlProperties}}/{{urnId}}/387999db-2c35-0c10-bea9-76f78ea2d06e/modelObjects

### Model Status
GET {{host}}{{urlProperties}}/{{urnId}}/modelStatus

############
### DDBB ###
############

### Database revit_model Elements
GET {{host}}{{urlModels}}/modelElements

### Database revit_model properties
GET {{host}}{{urlModels}}/modelProperties

### Database models
GET {{host}}{{urlModels}}/getModels

### Insert ELements
POST {{host}}{{urlProperties}}/insertElements
Content-Type: application/json

{
    "objectid": 3,
    "name": "Level 2",
    "externalId": "a9a13a2c-cb23-4a3a-bb87-986a41305963-1111177c",
    "type": "Wall",
    "created_at": "2025-05-16 12:00:00"
}





##PRUEBA MODEL COORDINATION
##Name: 00_Prueba Model Coordination
##Project ID: b.76947f01-cc26-47db-9681-fff27e5430ce
##Root Folder ID: urn:adsk.wipprod:fs.folder:co.D7F4NTwdRqqYqMaK-M01Yw
##Fichero Jimmy urn:adsk.wipprod:fs.file:vf.qRlvPHQhRgyoCEwCl3eElg?version=2

##TROJENA
##Name: Closed_21044_BCNE01_Trojena Ski Village Part 1
##Project ID: b.611f0303-7b8a-4f45-99f1-5da93b802707
##Root Folder ID: urn:adsk.wipprod:fs.folder:co.rCGm1uBRSzituVtkdSTuKA
