@host = http://localhost:3000
@projectId = b.76947f01-cc26-47db-9681-fff27e5430ce
@projectId2= b.611f0303-7b8a-4f45-99f1-5da93b802707
@projectIdVolta= b.7ce44dfd-1f18-44aa-957d-bc777c301389
@hubId = b.1bb899d4-8dd4-42d8-aefd-6c0e35acd825
@urnId= dXJuOmFkc2sud2lwcHJvZDpmcy5maWxlOnZmLnFSbHZQSFFoUmd5b0NFd0NsM2VFbGc_dmVyc2lvbj0y
@urnId2= dXJuOmFkc2sud2lwcHJvZDpmcy5maWxlOnZmLm9fb2pBVGRMVHRPZ3lRTVJvbk1lakE_dmVyc2lvbj0x
@urnId3= dXJuOmFkc2sud2lwcHJvZDpmcy5maWxlOnZmLnFSbHZQSFFoUmd5b0NFd0NsM2VFbGc_dmVyc2lvbj0z
@urnIdVolta= dXJuOmFkc2sud2lwcHJvZDpmcy5maWxlOnZmLll0Q3c2elN4UUllMjNldTBVdTkxQnc_dmVyc2lvbj0z
@itemId= urn:adsk.wipprod:dm.lineage:o_ojATdLTtOgyQMRonMejA
@itemId2= urn:adsk.wipprod:dm.lineage:qRlvPHQhRgyoCEwCl3eElg
@itemIdVolta= urn:adsk.wipprod:dm.lineage:YtCw6zSxQIe23eu0Uu91Bw
@urlAuth = /api/auth
@urlHub = /api/hub
@urlProjects = /api/projects
@urlFiles = /files
@urlRoot = /api/root
@urlProperties = /api/properties
@urlModels = /api/model
@urlElements = /api/elements
@accessToken = eyJhbGciOiJSUzI1NiIsImtpZCI6ImI4YjJkMzNhLTFlOTYtNDYwNS1iMWE4LTgwYjRhNWE4YjNlNyIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwczovL2F1dG9kZXNrLmNvbSIsImNsaWVudF9pZCI6ImhFVGlGanExaEpWQUVpUXNxTVNBajluSWdGQXZnUXRzeWJ2ZkFpV0dXdDJzQzA1WSIsInNjb3BlIjpbImRhdGE6Y3JlYXRlIiwiZGF0YTpyZWFkIiwiZGF0YTp3cml0ZSIsImJ1Y2tldDpjcmVhdGUiLCJidWNrZXQ6cmVhZCIsImJ1Y2tldDpkZWxldGUiLCJ2aWV3YWJsZXM6cmVhZCJdLCJpc3MiOiJodHRwczovL2RldmVsb3Blci5hcGkuYXV0b2Rlc2suY29tIiwiZXhwIjoxNzQ3MTI2NTQyLCJqdGkiOiJBVC01MTUxOWMwOS1kOWQwLTRlMmItOGQwYS04ZTczNGRkODFhZjIifQ.OJNUm_k4Sk0zFXGL4n5nbFUnDXte60ohGQn7w7OeelJD_Ziym-zg8Pf89m_H3E_0hNtdNd4H3FyRYLjgZusVHGMapjX4qQeIQ3DMxxrKe3mIk4JYra_erGQHmpm0C_TPKx4X8Sr7vFrZposL71gx3g4Uep3c-hcrMmH5FZBhJXtU2lmJjuARv_NrUMns94m78xeTmKeG1Doa857rtFp1K5PkSDqXqVA5D_TF8-AYCMiho6wOZradkDZrKwHSxI21m__NP-BqEc8tHVQ-2l4a0nKdag6gB9jg-Gake7gCgN_bXjDfsbA9tri4gds5hnTl3NjG4I99RX6u3FgoARCiUA


###################
### ACCESSTOKEN ###
###################

GET {{host}}{{urlAuth}}

###########
### HUB ###
###########

GET {{host}}{{urlHub}}

################
### PROJECTS ###
################

### Listar todos los proyectos
GET {{host}}{{urlProjects}}/{{hubId}}

### listar recursivamente todos las subcarpetas y ficheros finales del proyecto
GET {{host}}{{urlRoot}}/{{hubId}}/{{projectIdVolta}}{{urlFiles}}

### Listar el proyecto by Id
GET {{host}}{{urlProjects}}/{{hubId}}/{{projectIdVolta}}

### Obtener el Version ID del fichero
GET {{host}}{{urlRoot}}/{{projectIdVolta}}/{{itemIdVolta}}/versionId

### Metadata of .rvt
GET {{host}}{{urlProperties}}/meta/{{urnId3}}/metadata

### Hard Elements
GET {{host}}{{urlProperties}}/{{urnId3}}/919ace9e-438c-9400-4285-5c1eced5ebd5/allElementsHard

### Model Objects
GET {{host}}{{urlProperties}}/{{urnId3}}/919ace9e-438c-9400-4285-5c1eced5ebd5/modelObjects

### Model Status
GET {{host}}{{urlProperties}}/{{urnId}}/modelStatus

### Model Translate
POST {{host}}{{urlProperties}}/{{urnIdVolta}}/translate
Authorization: Bearer {{accessToken}}
Content-Type: application/json

############
### DDBB ###
############

### Database revit_model Elements
GET {{host}}{{urlElements}}/modelElements

### Database revit_model properties
GET {{host}}{{urlModels}}/modelProperties

### Database models
GET {{host}}{{urlModels}}/getModels

### Database Models By Id
GET {{host}}{{urlModels}}/getModels/1

### Database Model By Name
GET {{host}}{{urlModels}}/getModels/name/00_Prueba Model Coordination

### Insert ELements
POST {{host}}{{urlProperties}}/insertElements
Content-Type: application/json

{
    "objectid": 3,
    "name": "Level 2",
    "externalId": "a9a13a2c-cb23-4a3a-bb87-986a41305963-1111177c",
    "type": "Wall",
    "created_at": "2025-05-16 12:00:00"
}
